#server:
#  port: 7777
#  servlet:
#    session:
#      timeout:

# MongoDB Connection Settings
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: blog
#      username: wenjun
#      password: renzhe2zhuzhu

#    redis:
#      host: localhost
#      password:
#      port: 6379
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
#  docker:
#    compose:
#      lifecycle-management:

